pipeline {
  agent none
  
  stages {
    stage('Build') {
      when{
        changeset "**/worker/**"
      }
      agent {
        docker {
          image 'maven:3-jdk-8-slim'
          args '-v $HOME/.m2:/root/.m2'
        }
      }

      steps {
        echo "Building the app"
        dir('worker') {
          sh 'mvn compile'
        }
      }
    }
    stage('Test') {
      when{
        changeset "**/worker/**"
      }
      agent {
        docker {
          image 'maven:3-jdk-8-slim'
          args '-v $HOME/.m2:/root/.m2'
        }
      }
      steps {
        echo "Testing the app"
        dir('worker') {
          sh 'mvn clean test'
        }
      }
    }
    stage('Package') {
      when{
        branch 'master'
        changeset "**/worker/**"
      }
      agent {
        docker {
          image 'maven:3-jdk-8-slim'
          args '-v $HOME/.m2:/root/.m2'
        }
      }
            
      steps {
        echo "Packaging the app"
        dir('worker') {
          sh 'mvn package -DskipTests'
        }
        archiveArtifacts artifacts: 'worker/target/*.jar', fingerprint: true
      }
    }
    stage('docker-package') {
      agent any
      when{
        branch 'master'
        changeset "**/worker/**"
      }
      steps {
        echo "Building docker image"
        script{
          docker.withRegistry('https://index.docker.io/v1/','dockerlogin') {
            def workerImage = docker.build("pkoev86/worker:v${env.BUILD_ID}", "./worker")
            workerImage.push()
            workerImage.push("latest")
          }
        }
        
      }
    
    }
  }
  post {
      always {
        echo "Boo ya!"
      }
      success {
        echo "Dis one flew by"
      }
      failure {
        echo "Dis one din fly"
      }
      unstable {
        echo "Dis one flew by the cookoo's nest"
      }
      changed {
        echo "This will run only if the state of the Pipeline has changed"
        echo "For example, if the Pipeline was previously failing but is now successful"
      }
  }
